### ISSUE TITLE
Can't use arrows after last Microsoft Terminal update

### ISSUE THREAD

**Issue by Anessen97** [YaSuenag/SimpleCom#4]
Hello,
I use SimpleCom from Microsoft Terminal, but after the last update it doesn't work properly, because the arrows don't work.
Strangely, if I launch it directly, the arrows work fine.
Is it just me or did this occur to someone else?

**Comment by YaSuenag** [comment]
I've received same problem: https://github.com/YaSuenag/SimpleCom/issues/1#issuecomment-530201917

However I haven't do further investigation because it might caused by Windows Terminal.

I didn't try, but we might be able to avoid this issue if SimpleCom is started on cmd e.g. `cmd.exe SimpleCom.exe`.

**Comment by YaSuenag** [comment]
I refactored stdin handler in https://github.com/YaSuenag/SimpleCom/commit/a1109e2df0e025604ee960b0afda0fe4719a3ef1 . If you still interest in this issue, can you try this commit? (it is head of SimpleCom, so you can build master branch.)

Your comments are welcome!

**Comment by Anessen97** [comment]
I'll try to build it in the coming days.
Thank you for the heads up.

**Comment by Anessen97** [comment]
I built it on VS 2019 successfully and tried it on MS Terminal.
It worked flawlessly, arrow keys included.
I tested it on a U-Boot console of a SBC I had laying around.

Thank you very much for the fix, you're awesome!!!!

**Comment by YaSuenag** [comment]
Thank you for testing! I'm glad to hear it.

I will release new version includes this fix later.
