### ISSUE TITLE
Need don't show "GetOverlappedResult for WaitCommEvent" dialog option

### ISSUE THREAD

**Issue by shishirong** [YaSuenag/SimpleCom#51]
popup the dialog when disconnected is bad user experience, 
![image](https://github.com/user-attachments/assets/1632d82a-9bfb-43ce-86cd-a4a57e9e1ae0)

**Comment by YaSuenag** [comment]
Do you mean the dialog box when peripheral disconnects the session? I want to clarify the timing of the dialog.

**Comment by shishirong** [comment]
Yes, it is . 
sometimes the dialog popup is unwanted because it disrupts the flow when using `--auto-reconnect` and still requires clicking the dialog.  Perhaps logging a warning instead would be more appropriate.

Additionally, in my usage scenario, the `--auto-reconnect-pause` value should be specified in milliseconds.

(My usage scenario: a disconnection is expected, and I need it reconnected as soon as possible.)

**Comment by YaSuenag** [comment]
What version did you use? Can you try v1.2.4 (latest version)?

I tried v1.2.4 with Raspberry Pi 4 (Fedora 40) connected by serial gadget mode (USB OTG), then I didn't see any dialogs as you shown. Reconnection was started silently.

In addition, I think you can set `0` to `--auto-reconnect-pause` to reconnect immediately.  
I set `0` to reconnect pause seconds on SimpleCom dialog box, then the reconnection happened immediately when the device was disconnected.

I guess error dialog and the detection of disconnection show different behavior by serial devices (serial port controller in prescise). On combination of Raspberry Pi 4 and Linux USB OTG looks good, but we might see strange behavior on other devices.

**Comment by shishirong** [comment]
![image](https://github.com/user-attachments/assets/dd6f731f-cb52-4f7f-a0b6-62e8bfd534ea)

My run environment is [windows 10] + [microsoft-terminal] + [pwsh]

**Comment by YaSuenag** [comment]
I don't know why you see error dialog. If you see it on Windows 11 (with apply all of patch sets), I guess it is caused by serial port controller and/or device driver of your serial port.

Anyway, I cannot investigate more because I cannot reproduce it on my environment (Raspberry Pi 4, USB OTG) - it means I cannot fix. However, you are welcome to send me patches as PR.

**Comment by YaSuenag** [comment]
I added error code to the dialog in new commit https://github.com/YaSuenag/SimpleCom/commit/70e98eb7ea5bd01d08e51bc19a71792b6dbee4b2 . I use `FormatMessage` to convert error code to the message, but it often difficult to understand the situation - it might be useful to know (defined) error code like we write into the source code.

You have to build the letest source code by yourself, but I believe it helps you to check what happened. You can check error code in https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes .

**Comment by shishirong** [comment]
debug log is not found element when error dialog popup 
![image](https://github.com/user-attachments/assets/0f47daa2-c1b1-4393-bc8b-8713eee645c0)

**Comment by YaSuenag** [comment]
Thank you for sharing your console message. I think we can improve error handling when serial controller is detached, but I'm not sure what error code should be handled.

Your report shows 0x490 (`ERROR_NOT_FOUND`) at cancelling I/O - it is different from your first report (the error happened at stdout redirection from the device).

I need what error code would be issued when serial device is detached, but I've not yet found official reference about this. In addition, the behavior would be vary by device driver (it means device driver of serial controller). So the fix might be difficult...

Anyway, I do not want to suppress the dialog when error happens during shutdown phase (in the device) because it might be critical error which does not relate to shutdown sequence.

**Comment by YaSuenag** [comment]
According to [serial communication implementation in .NET Reference Source](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System/sys/system/IO/ports/SerialStream.cs#L1739-L1748), `WaitCommEvent` may return following error code. Can you check? You should see error code in hex in error dialog if you use the latest commit of SimpleCom (I believe you already use it).

* `ERROR_ACCESS_DENIED`
* `ERROR_BAD_COMMAND`
* `ERROR_DEVICE_REMOVED`

**Comment by shishirong** [comment]
![image](https://github.com/user-attachments/assets/e2624fdf-ca4a-4e64-af23-202b25508cf9)

**Comment by YaSuenag** [comment]
Thanks @shishirong to report this issue! I've created #52 for this issue. I believe the PR solves your problem, but I cannot test it on your environment. So I'm happy if you give me feedback. Thanks!

**Comment by shishirong** [comment]
yes, it is solved, thanks .
