### ISSUE TITLE
Ability to remember UTF-8 options to avoid having to click every time you open it

### ISSUE THREAD

**Issue by 776a7a68616f** [YaSuenag/SimpleCom#64]
Ability to remember UTF-8 options to avoid having to click every time you open it

**Comment by YaSuenag** [comment]
SimpleCom does not have any configuration file because it should be "simple".

I've targeted to use it on Windows Terminal. You can add `--utf8` into SimpleCom configuration, it would act like a preset configuration. 
![スクリーンショット 2024-11-07 181818](https://github.com/user-attachments/assets/f46e9971-8b41-4268-ab69-7a6c1f75db21)

**Comment by YaSuenag** [comment]
Close this issue because we can set UTF-8 check with `--show-dialog --utf8` command line options.
